var express = require('express');
var router = express.Router();

/* GET home page. */
router.get('/', function(req, res, next) {
  res.render('index', { title: 'Express' });
});


router.get('/search',function(req,res,next){
  res.render('resultlist',{title:'now I am here'});
});

router.get('/place',function(req,res,next) {
    res.render('place', {title: 'And now I am here :O'});
});

router.get('/headout', function(req, res, next) {
    var pikk= {
    house_number_supplement: '',
        cluster_rating_split: { '1': 3, '2': 5, '3': 7, '4': 8, '5': 35 },
    url: 'http://www.fabrikkan.is',
        distance: null,
        has_branches: true,
        indexed_at: '2016-10-02 21:08:19',
        keywords:
    [ 'borgari',
      'burger',
      'börger',
      'citizen',
      'fabrikka hamburger',
      'fabrikkan',
      'fabrikkuborgari',
      'food',
      'hamborgarafabrikkan',
      'hamborgari',
      'matur',
      'morhtens',
      'morthens',
      'restaurant',
      'simmi and jói',
      'simmi og jói',
      'tavern',
      'veitingahús',
      'veitingastaður',
      'íslenska hamborgarafabrikkan' ],
        rating_score: 310,
        hide_ssn: false,
        brand_background_color: '#ffffff',
        brand_banner_height: 398,
        sub_lines: [ [Object], [Object] ],
        url_pretty: 'www.fabrikkan.is',
        cluster_key: 'hamborgarafabrikkan',
        postal_code: 105,
        rating_count: 58,
        slug: 'islenska-hamborgarafabrikkan',
        service_page_path: 'hamborgarafabrikkan',
        national_id_number: '7107090170',
        logo_url_low: 'sala/logo/100x57/24816_1_1_HT0oa6p.png',
        hours_presentation: [ [Object], [Object] ],
        has_infopage: null,
        match_in_oskrad: false,
        has_ratings: null,
        slogan: null,
        vat_number: '103255',
        postal_station: '105 Reykjavík',
        occupation: 'Höfðatorgi',
        video_url: null,
        logo_url: 'sala/logo/120x70/24816_1_1_HT0oa6p.png',
        has_branded_page: true,
        cluster_rating_count: 58,
        twitter_link: null,
        categories:
    [ 'hamburger restaurants',
      'veitingahús',
      'restauracje serwujace hamburgery',
      'hamborgarastaðir',
      'restauracje',
      'restaurants' ],
        last_name: '',
        bold: true,
        distance_display: null,
        street: 'Katrínartúni',
        twitter_uid: null,
        has_coordinates: true,
        has_slogan: null,
        explanation: null,
        first_name: 'Íslenska Hamborgarafabrikkan',
        is_branch: false,
        description: null,
        cluster_rating_score: 310,
        logo_url_high: 'sala/logo/300x171/24816_1_1_HT0oa6p.png',
        additional_phones: [],
        address_nominative: 'Katrínartún 2',
        booking_link: null,
        subtype: null,
        fax: null,
        rating_comment_id: 3711,
        map_img_url: null,
        has_map_img: null,
        facebook_uid: null,
        phone:
    { operator: '07',
        pretty: '575 7575',
        number: '5757575',
        type: 'almenn',
        banned: false,
        country_code: '' },
    brand_banner_path: 'http://media.ja.is/sala/vorumerkjasida/banner/bannandi.png',
        municipality: 'Reykjavík',
        is_person: false,
        brand_banner_modified: '2016-10-02 00:00:00',
        is_open: false,
        postal_station_nominative: '105 Reykjavík',
        address: 'Katrínartúni 2',
        hours: 'sun-mid 11:00-22:00\nfim-lau 11:00-00:00',
        country: null,
        type: 'yellow',
        square_logo_url_small: null,
        branch_title: { en: [Object], is: [Object] },
    coordinates:
    { ja360_heading: 350.64966,
        lon: -21.907435,
        show_map_link: true,
        map_url: 'http://ja.is/kort/?q=%C3%8Dslenska%20Hamborgarafabrikkan%2C%20Katr%C3%ADnart%C3%BAni%202&x=358518&y=407935&z=8&type=map',
        ja360_image_x: 358541,
        ja360_image_url: 'http://stor-1.ja.is/preview/preview_1493514.jpg',
        y: 407935,
        x: 358518,
        has_360: true,
        ja360_image_y: 407946,
        ja360_image_id: 1053854,
        map_image_url: 'http://ja.is/kort/static/?x=358518&y=407935&z=7',
        lat: 64.144973,
        ja360_fov: 90,
        ja360_url: 'http://ja.is/kort/?q=%C3%8Dslenska%20Hamborgarafabrikkan%2C%20Katr%C3%ADnart%C3%BAni%202&x=358541&y=407946&z=8&ja360=1&ji=1053854&jh=351&fov=90&vlookat=0.0',
        ja360_vlookat: 0 },
    is_primary: true,
        middle_name: '',
        phonebook_id_number: '1493514',
        email: 'fabrikkan@fabrikkan.is',
        square_logo_url_large: null,
        instant_messaging_address: null,
        color: null,
        brand_banner_target: 'http://www.fabrikkan.is/',
        facebook_link: null,
        house_number: 2,
        cluster_rating_mean: 4.2,
        hashid: '21pnM',
        banned: false,
        brand_banner_width: 916,
        rating_display: true,
        common_id: '1493514',
        name: 'Íslenska Hamborgarafabrikkan',
        gift_certificate_link: null,
        social: [],
        has_description: null,
        rating_split: { '1': 3, '2': 5, '3': 7, '4': 8, '5': 35 },
    logo_url_medium: 'sala/logo/200x114/24816_1_1_HT0oa6p.png',
        rating_mean: 4.2
  };
    var key = process.env.AUTHKEY || '';
    res.render('headout', {title: 'Le Pikk', jaObject: pikk});

});

module.exports = router;
